<?php

namespace LTucillo\View;

class UpdateMessages extends Template
{
    public function getTemplate()
    {
        return 'update/notice';
    }

    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
    }
}
